Repository aeternity/superhero-ui, pull requests merged in 2020-05, with the labels that each got.

#435 Refactoring
  src/App.vue
  src/components/TipInput.vue
  src/components/TipsPagination.vue
  src/components/layout/MobileNavigation.vue
  src/components/layout/Navigation.vue
  src/components/layout/Overview.vue
  src/components/modals/MobileSendTipModal.vue
  src/components/onboarding/steps/Step5.vue
  src/components/tipRecords/TipComment.vue
  src/utils/i18nHelper.js
  src/utils/tippingContractUtil.js
  src/utils/util.js
  src/views/CreateProfile.vue
  src/views/Maintenance.vue
  src/views/Mission.vue
  src/views/Privacy.vue
  src/views/Terms.vue
  src/views/TipCommentsView.vue
  src/views/TipsList.vue
  src/views/UserProfileView.vue
Labels: status/review

#431 Added navigation tablets
  src/components/BackButtonRibbon.vue
  src/components/layout/MobileNavigation.vue
  src/components/layout/SendTip.vue
  src/locales/en.json
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/mutations.js
  src/styles/layout.scss
  src/views/TipsList.vue
Labels: status/review

#345 Feature card embedly previews
  public/index.html
  src/components/TipsPagination.vue
  src/components/tipRecords/TipRecord.vue
Labels: status/wip

#476 Create nested comments functionality
  src/components/SendComment.vue
  src/components/TipInput.vue
  src/components/tipRecords/TipComment.vue
  src/components/tipRecords/TipCommentList.vue
  src/components/tipRecords/TipRecord.vue
  src/locales/en.json
  src/views/SingleCommentView.vue
  src/views/TipCommentsView.vue
Labels: status/review

#498 Optimize Tip Section
  src/App.vue
  src/assets/blacklistedUrl.svg
  src/assets/defaultUrl.svg
  src/assets/iconClose.svg
  src/assets/iconError.svg
  src/assets/notVerifiedUrl.svg
  src/assets/verifiedUrl.svg
  src/components/AeButton.vue
  src/components/layout/FooterSection.vue
  src/components/layout/MobileNavigation.vue
  src/components/layout/RightSection.vue
  src/components/layout/SearchInput.vue
  src/components/layout/SendTip.vue
  src/components/layout/sendTip/SendTip.vue
  src/components/layout/sendTip/SendTipStatusMsg.vue
  src/components/layout/sendTip/UrlStatus.vue
  src/components/modals/MobileSendTipModal.vue
  src/locales/en.json
  src/locales/zh.json
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/mutations.js
  src/styles/_variables.scss
  src/styles/layout.scss
  src/utils/backend.js
  src/utils/util.js
  src/views/TipsList.vue
Labels: status/review

#496 Set tip message to be ontop of the preview
  src/components/tipRecords/TipComment.vue
  src/components/tipRecords/TipRecord.vue
Labels: status/review

#581 Release 0.1.6
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/defaultUrl.svg
  src/assets/iconDiamondActive.svg
  src/components/AeAmount.vue
  src/components/AeButton.vue
  src/components/AeInputAmount.vue
  src/components/Avatar.vue
  src/components/AvatarWrapper.vue
  src/components/BackButtonRibbon.vue
  src/components/Checkbox.vue
  src/components/FiatValue.vue
  src/components/Modal.vue
  src/components/SendComment.vue
  src/components/SuccessModal.vue
  src/components/ThreeDotsMenu.vue
  src/components/TipInput.vue
  src/components/TipsPagination.vue
  src/components/layout/FooterSection.vue
  src/components/layout/MobileNavigation.vue
  src/components/layout/Navigation.vue
  src/components/layout/Page.vue
  src/components/layout/RightSection.vue
  src/components/layout/SearchInput.vue
  src/components/layout/sendTip/SendTip.vue
  src/components/onboarding/steps/Step1.vue
  src/components/onboarding/steps/Step2.vue
  src/components/onboarding/steps/Step3.vue
  src/components/onboarding/steps/Step4.vue
  src/components/onboarding/steps/Step5.vue
  src/components/tipRecords/TipComment.vue
  src/components/tipRecords/TipRecord.vue
  src/locales/en.json
  src/locales/zh.json
  src/main.js
  src/router.js
  src/store/actions.js
  src/store/getters.js
  src/store/index.js
  src/store/mutation-types.js
  src/store/mutations.js
  src/styles/base.scss
  src/utils/aeternity.js
  src/utils/backend.js
  src/utils/util.js
  src/views/CreateProfile.vue
  src/views/FAQ.vue
  src/views/League.vue
  src/views/Maintenance.vue
  src/views/Mission.vue
  src/views/Privacy.vue
  src/views/SingleCommentView.vue
  src/views/Terms.vue
  src/views/TipCommentsView.vue
  src/views/TipsList.vue
  src/views/UserProfileView.vue
  src/views/admin/Tracing.vue
Labels: status/hodl
