Repository aeternity/superhero-ui, pull requests merged in 2020-09, with the labels that each got.

#786 Spanish translation
  src/locales/es.json
Labels: area/locales

#783 Refactor modals
  src/App.vue
  src/components/AlertModal.vue
  src/components/layout/sendTip/SendTip.vue
  src/components/layout/sendTip/SendTipStatusMsg.vue
  src/components/tipRecords/TipRecord.vue
  src/main.js
  src/store/index.js
  src/store/plugins/modals.js
  src/views/TipsAndComments.vue
  src/views/modals.js
Labels: area/refactoring

#812 Lower z-index on three dot menu
  src/components/Modal.vue
Labels: needs testing
